# Generated by Django 5.2.7 on 2025-10-14 18:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NrZp', models.CharField(db_index=True, max_length=50, verbose_name='Numer zlecenia')),
                ('Data', models.DateField(verbose_name='Data produkcji')),
                ('Zmiana', models.CharField(choices=[('I', 'Zmiana I'), ('II', 'Zmiana II'), ('III', 'Zmiana III')], max_length=3, verbose_name='Zmiana')),
                ('Rolka', models.IntegerField(verbose_name='Numer rolki')),
                ('NrWytl', models.IntegerField(verbose_name='Nr wytłaczarki')),
                ('Rodzaj', models.IntegerField(verbose_name='Rodzaj folii')),
                ('DlugRolkiProd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Długość rolki')),
                ('WagaRolkiProd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Waga rolki')),
                ('Slimak', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ślimak')),
                ('Walce', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Walce')),
                ('Wynikowa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wynikowa')),
                ('Wynik', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wynik')),
                ('Mieszanka', models.CharField(blank=True, max_length=100, verbose_name='Mieszanka')),
                ('Uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('UserName', models.CharField(max_length=150, verbose_name='Operator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rolka',
                'verbose_name_plural': 'Rolki',
                'ordering': ['-Data', '-Zmiana', 'Rolka'],
                'indexes': [models.Index(fields=['NrZp', 'Data'], name='events_rolk_NrZp_93e753_idx'), models.Index(fields=['UserName', 'Data'], name='events_rolk_UserNam_4b7580_idx')],
                'unique_together': {('NrZp', 'Rolka')},
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NrZp', models.CharField(max_length=50, unique=True, verbose_name='Numer zlecenia')),
                ('Data', models.DateField(verbose_name='Data')),
                ('Status', models.IntegerField(choices=[(0, 'Planowane'), (1, 'W realizacji'), (2, 'Zrealizowane'), (3, 'Anulowane')], default=0, verbose_name='Status')),
                ('Priorytet', models.IntegerField(choices=[(0, 'Wysoki'), (1, 'Średni'), (2, 'Niski')], default=1, verbose_name='Priorytet')),
                ('Rodzaj', models.IntegerField(choices=[(0, 'HDPE'), (1, 'LDPE'), (2, 'MDPE')], verbose_name='Rodzaj folii')),
                ('IloscZlec', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość zlecona')),
                ('SzerWorka', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Szerokość worka [mm]')),
                ('SzerRekawa', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Szerokość rękawa [mm]')),
                ('DlugWorka', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Długość worka [mm]')),
                ('GrubWorka', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Grubość worka [μm]')),
                ('WagaFoliZlec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Waga folii')),
                ('DlugFoliPlan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Długość folii plan')),
                ('NrWytl', models.IntegerField(default=0, verbose_name='Nr wytłaczarki')),
                ('Tasma', models.BooleanField(default=False, verbose_name='Taśma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['Status', 'Priorytet'], name='events_zamo_Status_ae01c3_idx'), models.Index(fields=['NrZp'], name='events_zamo_NrZp_2726ad_idx')],
            },
        ),
    ]
