# Generated by Django 4.1.7 on 2024-02-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rolki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NrZp', models.CharField(max_length=20, verbose_name='NrZp')),
                ('Data', models.DateField()),
                ('Zmiana', models.CharField(max_length=10)),
                ('Rolka', models.IntegerField()),
                ('NrWytl', models.IntegerField()),
                ('Rodzaj', models.IntegerField()),
                ('DlugRolkiProd', models.FloatField()),
                ('WagaRolkiProd', models.FloatField()),
                ('Walce', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Slimak', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Wynikowa', models.FloatField()),
                ('Wynik', models.FloatField()),
                ('Mieszanka', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('Uwagi', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('UserName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NrZp', models.CharField(max_length=20, verbose_name='NrZp')),
                ('Data', models.DateField()),
                ('Artykul', models.CharField(max_length=30)),
                ('NrWyt', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('Rodzaj', models.IntegerField()),
                ('Priorytet', models.IntegerField()),
                ('Tasma', models.IntegerField()),
                ('Uwagi', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('IloscZlec', models.IntegerField()),
                ('SzerWorka', models.IntegerField()),
                ('SzerRekawa', models.IntegerField()),
                ('Zakladka', models.FloatField()),
                ('DlugWorka', models.IntegerField()),
                ('GrubWorka', models.IntegerField()),
                ('DolneOdch', models.IntegerField()),
                ('DlugFoilPlan_Korekta', models.FloatField()),
                ('WagaFoliZlec', models.FloatField()),
                ('DlugFoliPlan', models.FloatField()),
                ('IloscRolekZlec', models.FloatField()),
                ('DlugRolkiZlec_Korekta', models.FloatField()),
                ('DlugRolkiPlan', models.FloatField()),
                ('DlugFoliZlec_Korekta', models.FloatField()),
                ('WagaRolkiZlec', models.FloatField()),
            ],
        ),
    ]
