# Generated by Django 5.2.7 on 2025-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Planowane'), (1, 'W realizacji'), (2, 'Zrealizowane'), (3, 'Anulowane')], default=0, verbose_name='Status'),
        ),
    ]
