# Generated by Django 4.1.7 on 2023-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_zamowienie_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imieNazwisko', models.CharField(max_length=40)),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=40)),
                ('uprawnienia', models.IntegerField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rolki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NrZp', models.CharField(max_length=20, verbose_name='NrZp')),
                ('Data', models.DateField()),
                ('Zmiana', models.CharField(max_length=10)),
                ('Rolka', models.IntegerField()),
                ('NrWytl', models.IntegerField()),
                ('DlugRolkiProd', models.FloatField()),
                ('WagaRolkiProd', models.FloatField()),
                ('Walce', models.FloatField()),
                ('Slimak', models.FloatField()),
                ('Wynikowa', models.FloatField()),
                ('Wynik', models.FloatField()),
                ('Mieszanka', models.CharField(max_length=40)),
                ('Uwagi', models.CharField(max_length=40)),
            ],
        ),
    ]
