# Generated by Django 4.1.7 on 2023-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_pracownik_rolki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pracownik',
        ),
        migrations.AddField(
            model_name='rolki',
            name='Rodzaj',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolki',
            name='UserName',
            field=models.CharField(default='Tomek', max_length=40),
            preserve_default=False,
        ),
    ]
