# Generated by Django 5.2.7 on 2025-10-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_zamowienie_status'),
        ('events', '0003_zamowienie_legacy_fields'),
    ]

    operations = [
    ]
