# Generated by Django 5.2.7 on 2025-10-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_backfill_legacy_columns'),
        ('events', '0004_merge_20251026_1510'),
    ]

    operations = [
    ]
