# Generated by Django 4.1.7 on 2023-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_zamowienie_barwnik_alter_zamowienie_kod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='Barwnik',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='Kod',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='MMK',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='Uwagi',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
