# Generated by Django 4.1.7 on 2023-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_rolki_slimak_alter_rolki_walce'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='Priorytet',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='Tasma',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolki',
            name='Slimak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolki',
            name='Walce',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
